### ISSUE TITLE
Some way to declare global variables?

### ISSUE THREAD

**Issue by FezVrasta** [bryanburgers/node-mustache-express#12]
I'd like to automatically add a variable to the context when I use res.render();

Is there some way?

Example:

```
js:
global = glob
res.render("index", {foo: "bar"});

template:
{{foo}} {{global}}

output:
bar glob
```

Thanks.

**Comment by popkutty** [comment]
@FezVrasta How to access locals in mustache expression?

**Comment by ppKrauss** [comment]
Google show this page  with NO SOLUTION HERE. **Please compleat this page with a link to official documentation**. 
----
I found some clues at https://github.com/bobthecow/mustache.php/wiki/Variable-Resolution

The name of this topic is "Mustache template variable resolution".
