### ISSUE TITLE
mustache version vulnerable

### ISSUE THREAD

**Issue by faust64** [bryanburgers/node-mustache-express#18]
Hi,

Using snyk checking for potential vulnerabilities in packages I install, I'm pointed out that mustache-express pulls an old version of mustache, that could be problematic (https://snyk.io/test/npm/mustache/0.8.2, https://snyk.io/test/npm/mustache-express/).

There's a large version gap, although the changelog doesn't look that scary, ... Not being sure what it would imply yet: would you consider upgrading your dependencies? Need a hand?

Thanks!

**Comment by bryanburgers** [comment]
Made you an admin on this project, as per http://felixge.de/2013/03/11/the-pull-request-hack.html. Be good, do good work, have fun.

**Comment by faust64** [comment]
Thanks, I'll give it a look very soon.

**Comment by faust64** [comment]
forgot to reference this issue from my PR: https://github.com/bryanburgers/node-mustache-express/pull/19

I'm not familiar with npm publication process. Let me know if you need more from me. We're not in a rush/purely cosmetic, ...
Thanks.

**Comment by andrewcpacifico** [comment]
Hi @bryanburgers,

Could you please publish this new release on npm?

Thanks.

**Comment by redhat-raptor** [comment]
Hello, when I npm install mustache-express I am getting the following version:

└─┬ mustache-express@1.2.2 
  ├── async@0.2.10 
  ├── lru-cache@2.5.2 
  └── mustache@0.8.2 

I expected mustache to be ~2.3.0. Any idea?

**Comment by faust64** [comment]
We would need someone with write privileges on the corresponding package @npm-registry, to publish a release.
Can you do this @bryanburgers ? Or do you want me to give it a shot? I suppose I can create an account over there.

**Comment by bryanburgers** [comment]
It's something I can do. I was really trying to hand off this project to anybody else. I would love to give the npm rights to somebody.

**Comment by faust64** [comment]
Allright, sent you a mail with my npmjs username, let's do this when you'll have time.

**Comment by bryanburgers** [comment]
@faust64 You are now a collaborator on the npm package. Push away.

**Comment by faust64** [comment]
Allright, looks like it worked.
Checking .... Would close by tomorrow, if all goes well.
Thanks again!
