### ISSUE TITLE
Template not rendering in layout

### ISSUE THREAD

**Issue by redhat-raptor** [bryanburgers/node-mustache-express#21]
Hello,

I configured mustache-express in app as below:

```
var app = express();
app.engine('mustache', mustacheExpress(__dirname + '/views', '.mustache'));
app.set('view engine', 'mustache');
app.set('views', __dirname + '/views');
app.set("layout", "layout");

```
And in my views dir I have the following:

- layout.mastache
- index.mustache

And from controller when I render my index template:
```
router.get('/', function(req, res, next) {
  res.render('index');
});

```
It renders the layout well however the content of index.mustache does not get rendered in layout.

Here is my layout:

```
<div id="wrapper">
    {{{body}}}
</div>

```
I expected {{{body}}} to be replaced by the content of index.mustache. Am I missing something?

**Comment by faust64** [comment]
Are you sure you can instantiate `mustacheExpress` with that second argument?
Looks like feeding in an extension, [you don't need to enter the leading dot](https://github.com/bryanburgers/node-mustache-express/blob/master/mustache-express.js#L146).

Now, when you run `res.render('index')`, I think you need to set some substitutions. Could look like;
```
res.render('index', { body: 'some body" });
```

**Comment by redhat-raptor** [comment]
Hello there, thanks for your reply!

Actually [in the source code](https://github.com/bryanburgers/node-mustache-express/blob/master/mustache-express.js#L137) if the extension is passed it uses it or it uses `'.' + options.settings['view engine']`. In the constructor I did pass the extension explicitly. May be I could just omit `app.set('view engine', 'mustache');`

`res.render('index', { body: "my awesome body" })` would surely get rendered in layout since the layout has {{{body}}} placeholder. However I thought if I rendered a template using `res.render()`, it would automatically get passed to layout as the body variable.

**Comment by faust64** [comment]
You're right regarding extension/constructor, read too fast. The dot is only added if passed by constructor.

I'm not completely familiar with that library yet, ... looks like layout support was added a couple years back. Commit includes unit tests you may want to look at:
 - [commit including unit tests](https://github.com/bryanburgers/node-mustache-express/commit/152d400d916a94603fae7f8af45b2ebd16b23076)
 - [PR](https://github.com/bryanburgers/node-mustache-express/pull/11)
 - [issue](https://github.com/bryanburgers/node-mustache-express/issues/7)

In particular, it seems like the variable replaced in the test layout is named `yield`, and not `body`.

**Comment by LucStr** [comment]
I Just faced the same issue. 

you do not put 
`{{{body}}}`
as placeholder, but instead 
`{{{yield}}}`

Your Layout might look something like this: 

```
<html>
    <head>
        <title>Title</title>
    </head>
    </body>
        <div>Header</div>
        {{{yield}}}
        <div>Footer</div>
    </body>
</html>
```

As for the configuration you can use something like this: 

```
app.engine('mustache', mustacheExpress(viewFolder, '.mustache'));

app.set('view engine', 'mustache');
app.set('views', __dirname + '/../views');
app.set("layout", "layout");

```

works like a charm!
