### ISSUE TITLE
Root layout doesn't receive data

### ISSUE THREAD

**Issue by umaar** [bryanburgers/node-mustache-express#22]
Oh hey, say I do

```js

...
app.set('layout', 'layout');
...

// later
res.render('index', {
   title: 'This is the title'
});
```

The file `index.mustache` _will_ receive the `title` but `layout.mustache` _will not_. Any chance you could add support for this? It'd be useful since the root layout typically displays things like titles/flash messages etc., but if it can't receive any data, this won't be possible.

Thanks!

**Comment by faust64** [comment]
Hi,

If you'ld like to contribute a PR addressing this: I'ld be glad to merge it.

Thanks!

**Comment by faust64** [comment]
Thanks! Merged and published to npmjs.
