### ISSUE TITLE
Dynamic template on layout

### ISSUE THREAD

**Issue by cmarrero01** [bryanburgers/node-mustache-express#23]
HI,

I want to load a partial that hes name is saved on an array.. like this..

`{{#data.home}}
        {{>templates/blocks/{[{blockType.partial}}}}
        {{/data.home}}`

Where blockType.partial is equal to the string "b1" who is the name of the partial in this case..

Its posible do that?

Best

**Comment by nullivex** [comment]
This is not the same approach you took but I believe this accomplishes the same idea of having 'dynamic' view elements.

https://github.com/bryanburgers/node-mustache-express/pull/28

**Comment by nullivex** [comment]
With PR#28 being merged I think this can be closed. @cmarrero01 any thoughts?

**Comment by faust64** [comment]
@cmarrero01 did not answer in a while, I'll trust @nullivex on that one. Closing.
Thanks for your contribution!

**Comment by stuartjnelson** [comment]
@nullivex this is exactly what I'm trying to do. Sorry from the  PR I can't workout how you've done it. What @cmarrero01 suggested is what I was hoping to be able to achieve. Eg;

`data.json`
```
{
  "partial": "image",
  "src": "/image.jpg"
}
```

`view.mst`
```
{{> (partial) }}
```

`image.mst`
```
<img src="{{ src }}" alt="">
```

Is this possible?
