### ISSUE TITLE
no option to change the `tags` options 

### ISSUE THREAD

**Issue by perymimon** [bryanburgers/node-mustache-express#31]
it look like there is two ways to update mustache tags. 

1. 
``` javascript
var mustache = require('mustache');
mustache.tags = ['[[',']]']
```
2.
```javascript
mustache.render = function render (template, view, partials, tags)
```

But no one of them available for `node-mustache-express` users ...

**Comment by faust64** [comment]
Hi,

Sorry for the delay, just released a new version.
You'll find a new unit test (`test/test12`) with a first sample of how to use this. Basically, just add your own tags array before the callback argument.
If you're up for it, we could use some PR documenting this. Or additional unit tests.

Regards.
