### ISSUE TITLE
Update Async to Latest Version to remove Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by phobos665** [bryanburgers/node-mustache-express#34]
Currently the Async Library used in this repo is very out of date and has a high-class vulnerability. 

Snyk Link: https://security.snyk.io/vuln/SNYK-JS-ASYNC-2441827

**Comment by faust64** [comment]
Snyk itself doesn't list mustache-express as vulnerable
While our package.json mentions ~3.2.0, there's no reason someone installing mustache-express would still end with a vulnerable async, would they?
Feel free to submit a PR.
